# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: appmusicfull
services:
  mysql:
    image: mysql:9.0.1
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=appMusicFull
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password

    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-mysqlx --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysql', '-e', 'SHOW DATABASES;']
      interval: 5s
      timeout: 5s
      retries: 10
